### PR TITLE
Add documentation for Claudia

### PR DESCRIPTION
**Pull request by SaxenaKaustubh**
Add Claudia's documentation to close https://ripplelabs.atlassian.net/browse/RIP-881

### CODE REVIEW

**Comment by SaxenaKaustubh** [comment]
@maria-robobug I am definitely okay with this idea. It also gives us more flexibility if we need to publish updates. Would we need to consult your team before publishing updates to the documentation though?

**Comment by maria-robobug** [comment]
> I am definitely okay with this idea. It also gives us more flexibility if we need to publish updates. Would we need to consult your team before publishing updates to the documentation though?


@SaxenaKaustubh, @amarantha-k I think it would be useful to have us review the documentation for Claudia when there's a significant change. Plus it will help with any future tutorials we may want to write for Claudia on the opensource.ripple.com docs too 👍🏾 .

**Comment by SaxenaKaustubh** [comment]
Sounds good. Can you review the documentation on [PyPi](https://pypi.org/project/claudia/) and let me know your thoughts? I will also publish the changes to only include a link to the existing Claudia documentation page.

**Comment by SaxenaKaustubh** [comment]
@maria-robobug I have updated the documentation link. When you get a chance, can you please have a look at PyPi's documentation?

**Comment by amarantha-k** [comment]
Based on the discussions (here and offline), it looks like everyone is in agreement to host the documentation in [one place](https://pypi.org/project/claudia/) and link to the Claudia project & docs as needed.   

Please confirm that this PR can be closed without merging.

**Comment by SaxenaKaustubh** [comment]
@amarantha-k the current MR introduces the links to Claudia homepage and should still be merged. Moreover, I am still seeking a review of the documentation available [here](https://pypi.org/project/claudia/).

**Comment by oeggert** [comment]
I've added the link from this PR to #77 . Closing this PR

**Comment by oeggert** [comment]
I've added the link to Claudia in #77

**Pull request closed without merging**
